version: '3'
services:
  usermgmt-client:
    image: client
    build:
      context: ./client
    ports:
      - "4200:80"
  usermgmt-service:
    image: native/usermgmt-service
    build:
      context: .
      dockerfile: usermgmt-server/src/main/docker/Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - db-test
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://db-test:5432/quarkusdb"
  db-test:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quarkusdb